name: CI

on:
  push:
    branches: [ main ]
    
jobs:
  
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: actions/checkout@v3
      - name: Setup Keystore File
        run: |
         echo "${{ secrets.TEMPLATEKEYSTORE }}" > template.keystore
          gpg -d --passphrase "${{ secrets.KEYSTORE_PASSWORD_GPG }}" --batch template.keystore > template.keystore
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: '7.0.302' 

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build and Publish
        run: dotnet publish -c Release -f net7.0-android33.0 /p:AndroidSigningKeyStore=template.keystore /p:AndroidSigningKeyAlias=template /p:AndroidSigningKeyPass="${{ secrets.KEYSTORE_PASSWORD }}" /p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASSWORD_ALIAS }}" --no-restore
        
      - name: Install App Center CLI
        run: npm install -g appcenter-cli
        
      - name: Upload Android app to App Center
        run: appcenter distribute release --silent --file ./MobileTemplate.Droid/bin/Release/com.companyname.mobiletemplate-Signed.apk --app rafael.gomez-arkanosoft.com/Template-Maui-android --group Collaborators --token ${{ secrets.Template }}
