name: CI

on:
  push:
    branches: [ main ]
    
jobs:
  
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: '7.0.302' 

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build and Publish
        run: dotnet publish -c Release -f net7.0-android33.0 --no-restore -o ./publish
        
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: ../com.companyname.mobiletemplate.apk
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE}}
          alias: ${{ secrets.KEYSTORE_PASSWORD_ALIAS }}
          keyStorePassword: ${{ secrets.TEMPLATEKEYSTORE}}
  
      - name: Install App Center CLI
        run: npm install -g appcenter-cli
        
      - name: Upload Android app to App Center
        run: appcenter distribute release --app rafael.gomez-arkanosoft.com/Template-Maui-android --group Collaborators --token ${{ secrets.Template }} --file ./publish/com.companyname.mobiletemplate-signed.apk
