name: CI

on:
  push:
    branches: [ main ]
    
jobs:
  
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: '7.0.302' 

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build and Publish
        run: dotnet publish -c Release -f net7.0-android33.0 /p:AndroidSigningKeyStore=template.keystore /p:AndroidSigningKeyAlias=template /p:AndroidSigningKeyPass="${{ secrets.KEYSTORE_PASSWORD }}" /p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASSWORD_ALIAS }}" --no-restore -o ./publish
        
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install JDK
        run: brew install openjdk@17

      - name: Install Android SDK
        run: brew install --cask android-sdk

      - name: Configure Android SDK
        run: echo 'export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"' >> $GITHUB_ENV
        
      - name: Sign APK
        run: |
          echo "${{ secrets.TEMPLATEKEYSTORE }}" | base64 --decode > ~/.android/template.keystore
          brew install openjdk@17
          export PATH="/usr/local/opt/openjdk@17/bin:$PATH"
          cd ./publish
          zipalign -v -p 4 com.companyname.mobiletemplate.apk com.companyname.mobiletemplate-aligned.apk
          export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"
          export JAVA_HOME="/usr/local/opt/openjdk@17"
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/tools/bin:$PATH"
          apksigner sign --ks ~/.android/template.keystore --ks-pass pass:"template" --key-pass pass:"template" --out app-signed.apk

      - name: Install App Center CLI
        run: npm install -g appcenter-cli
        
      - name: Upload Android app to App Center
        run: appcenter distribute release --app rafael.gomez-arkanosoft.com/Template-Maui-android --group Collaborators --token ${{ secrets.Template }} --file ./publish/com.companyname.mobiletemplate-signed.apk
