name: CI

on:
  push:
    branches: [ main ]
    
jobs:
  
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: '7.x' 

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Build and Publish
        run: dotnet publish -c Release -o ./publish

      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up JDK
        run: |
          echo "JAVA_HOME=$(whereis java)" >> $GITHUB_ENV

      - name: Sign APK
        run: |
          sudo apt-get install -y zip
          mkdir -p ~/.android
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > ~/.android/template.keystore
          echo "$KEYSTORE_PROPERTIES_BASE64" | base64 --decode > keystore.properties
          cd ./publish
          zipalign -v -p 4 app.apk app-aligned.apk
          apksigner sign --ks ~/.android/template.keystore --ks-pass env:KEYSTORE_PASSWORD --key-pass env:KEY_PASSWORD --out app-signed.apk app-aligned.apk
          
      - name: Install App Center CLI
        run: npm install -g appcenter-cli
        
      - name: Upload Android app to App Center
        run: appcenter distribute release --silent --file ./MobileTemplate.Droid/bin/Release/com.companyname.mobiletemplate-Signed.apk --app rafael.gomez-arkanosoft.com/Template-Maui-android --group Collaborators --token ${{ secrets.Template }}
